# App Requests

### Benefit ###

### Get Module Request
GET http://13.215.206.103/api/management/benefit
Content-Type: application/json

### Create Module Request
POST http://13.215.206.103/api/management/benefit
Content-Type: application/json

{
  "name": "Transportation allowance",
  "type": "credit",
  "description": "This is a transportation allowance benefit",
  "active": true
}

### Update Module Request
PUT http://13.215.206.103/api/management/benefit/1
Content-Type: application/json

{
  "active": true
}

### Delete Module Request
DELETE http://13.215.206.103/api/management/benefit/1
Content-Type: application/json