# App Requests

### ROLE ###

### Get Module Request
GET http://13.215.206.103/api/employee-type
Content-Type: application/json

### Create Module Request
POST http://13.215.206.103/api/employee-type
Content-Type: application/json

{
  "name": "sample employee",
  "description": "This is only a sample...",
  "active": true
}

### Update Module Request
PUT http://13.215.206.103/api/employee-type/5
Content-Type: application/json

{
  "active": true
}

### Delete Module Request
DELETE http://13.215.206.103/api/employee-type/6
Content-Type: application/json