# App Requests

### ROLE ###

### Get Module Request
GET http://localhost:3000/api/modules
Content-Type: application/json

### Create Module Request
POST http://localhost:3000/api/modules
Content-Type: application/json

{
  "name": "User",
  "description": "User module",
  "active": true,
  "link": "/users"
}

### Get Module by ID Request
GET http://localhost:3000/api/modules/16
Content-Type: application/json

### Update Module Request
PUT http://localhost:3000/api/modules/4
Content-Type: application/json

{
  "name": "Module",
  "description": "Module module",
  "link": "/modules",
  "active": true
}

### Delete Module Request
DELETE http://localhost:3000/api/modules/4
Content-Type: application/json