# App Requests

### ROLE ###

### Get Module Request
GET http://13.215.206.103/api/modules
Content-Type: application/json

### Create Module Request
POST http://13.215.206.103/api/modules
Content-Type: application/json

{
  "name": "Employee type",
  "description": "Employee type module",
  "active": true,
  "link": "/management/Employee type"
}

### Get Module by ID Request
GET http://13.215.206.103/api/modules/16
Content-Type: application/json

### Update Module Request
PUT http://13.215.206.103/api/modules/1
Content-Type: application/json

{
  "active": true
}

### Delete Module Request
DELETE http://13.215.206.103/api/modules/4
Content-Type: application/json