# App Requests

### ROLE ###

### Get All Permissions Request
GET http://localhost:3000/api/permissions
Content-Type: application/json

### Get Permission by ID Request
GET http://localhost:3000/api/permissions/6
Content-Type: application/json

### Create Permission Request
POST http://localhost:3000/api/permissions
Content-Type: application/json

{
  "action": "create",
  "moduleId": 3,
  "description": "",
  "active": true
}

### Update Permission Request
PUT http://localhost:3000/api/permissions/8
Content-Type: application/json

{
  "active": true
}

### Delete Permission Request
DELETE http://localhost:3000/api/permissions/8
Content-Type: application/json