# App Requests

### ROLE ###

### Get All Roles Request
GET http://13.215.206.103:3000/api/roles
Content-Type: application/json

### Get Role by ID Request
GET http://13.215.206.103:3000/api/roles/5
Content-Type: application/json

### Create Role Request
POST http://13.215.206.103:3000/api/roles
Content-Type: application/json

{
  "name": "admin 2",
  "description": "Admin role",
  "active": true,
  "permissions": [
    {
      "permissionId": 1
    },
    {
      "permissionId": 2
    }
  ]
}

### Update Role Request
PUT http://13.215.206.103:3000/api/roles/1
Content-Type: application/json

{
  "description": "Admin role",
  "active": true,
  "permissions": [
    {
      "permissionId": 1
    },
    {
      "permissionId": 2
    },
    {
      "permissionId": 3
    },
    {
      "permissionId": 4
    },
    {
      "permissionId": 5
    },
    {
      "permissionId": 6
    },
    {
      "permissionId": 7
    },
    {
      "permissionId": 8
    },
    {
      "permissionId": 9
    },
    {
      "permissionId": 11
    },
    {
      "permissionId": 12
    }
  ]
}

### Delete Role Request
DELETE http://13.215.206.103:3000/api/roles/1
Content-Type: application/json

### Retrieve Role Request
PUT http://13.215.206.103:3000/api/roles/retrieve/1
Content-Type: application/json