# App Requests

### Task ###

### Get Task Request
GET http://13.215.206.103/api/management/task
Content-Type: application/json

### Create Task Request
POST http://13.215.206.103/api/management/task
Content-Type: application/json

{
  "name": "Sample task 1",
  "description": "Sample task descripotion",
  "active": true
}

### Update Task Request
PUT http://13.215.206.103/api/management/task/1
Content-Type: application/json

{
  "active": true
}

### Delete Task Request
DELETE http://13.215.206.103/api/management/task/1
Content-Type: application/json